# -*- coding: utf-8 -*-
"""Comaprison_Pricing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfLiva4SG1PsyXhkBtJzEEGL25y62KyX
"""

import numpy as np
import math
import random

import scipy
from scipy.optimize import minimize
from scipy.optimize import fsolve

#y\ =-x^{5\ }\ +\ 12x^{4}-46x^{3}+\ 418\cdot x^{2}\ -50\cdot x\ +\ 40
# true_coeff = np.array([-150,480,-165,22,-1])
# true_coeff = np.array([0,1.1,-0.5])

from tqdm import tqdm

import torch

!pip install gpytorch
import gpytorch

from scipy.stats import norm

def func_revenue(price):
    # p_arr = np.array([1,price,price**2,price**3,price**4])
    # return np.sum(p_arr*true_coeff)
    return 100*np.exp(-(price-5)**2/20)

import scipy
from scipy.stats import norm

def compute_barycentre():
  def equations(p):
    p2,p3,p4= p
    return (1/p2 + 1/(p2-p3)+ 1/(p2-p4) + 1/(p2-1),
          1/p3 + 1/(p3-p2)+ 1/(p3-p4) + 1/(p3-1),
          1/p4 + 1/(p4-p2)+ 1/(p4-p3) + 1/(p4-1),
          )
  b2_init = np.random.uniform(0,1)
  b3_init = np.random.uniform(0,1)
  b4_init = np.random.uniform(0,1)
  # b5_init = np.random.uniform(0,1)
  b2,b3,b4= fsolve(equations,(b2_init,b3_init,b4_init))
  return np.array([0.,b2,b3,b4,1.])

# barycentric_spanner = compute_barycentre()
barycentric_spanner = np.array([0.,0.5,1.])

def p_vector(p):
        p_vec = np.array([1,p,p**2])
        return p_vec.reshape(len(p_vec),1)

# var_cov_inv = np.zeros((5,5))
# for b in barycentric_spanner:
#         b_vec = p_vector(b)
#         var_cov_inv += b_vec@np.transpose(b_vec)

barycentric_spanner

# var_cov_inv

def Thompson():
    epsilon_array = []
    def p_vector(p):
        p_vec = np.array([1,p,p**2])
        return p_vec.reshape(len(p_vec),1)

    def g_fun(p,*args):
          p_vec = np.array([1,p,p**2])
          coeff_array = args
          return -np.sum(coeff_array*p_vec)
    var_cov_inv = np.zeros((3,3))
    for b in barycentric_spanner:
        b_vec = p_vector(b)
        var_cov_inv += b_vec@np.transpose(b_vec)

    var_cov = np.linalg.inv(var_cov_inv)
    mu_ = np.array([0,0,0])
    pl = 0
    ph = 2
    w = np.random.multivariate_normal(np.array([0,0,0]),var_cov)
    price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (w),bounds = [(pl,ph)])["x"][0]
    p_array = []
    p_curr = p_vector(price_estimate)
    p_array.append(price_estimate)
    reven_array = []
    def update_mean(rev,p_ar):
      sum = 0
      for i in range(len(rev)):
          price = p_ar[i]
          p = p_vector(price)
          sum += rev[i]*p/100
      return sum

    def update_mat(p_ar):
        sum = 0
        for i in range(len(p_ar)):
            price = p_ar[i]
            p = p_vector(price)
            sum += (p@np.transpose(p))/100
        return sum
    error = 0
    for i in tqdm(range(100)):
        # rev_curr = (true_coeff.reshape(1,3)@p_curr)[0][0]+np.random.normal(0,10)
        rev_curr = func_revenue(price_estimate)+np.random.normal(0,10)
        reven_array.append(rev_curr)
        var_copy = var_cov
        mu_copy = mu_
        var_cov = np.linalg.inv(np.linalg.inv(var_copy) + update_mat(p_array))
        # np.linalg.eig(var_cov)
        min_ev = np.min(np.linalg.eig(var_cov)[0])
        if min_ev <= 0:
            var_cov += np.diag(np.array([1e-5,1e-5,1e-5]))
        mu_ = var_cov@(np.linalg.inv(var_copy)@mu_copy.reshape(3,1) + update_mean(reven_array,p_array))
    #     mu_ = var_cov@( rev_curr*p_curr/100)
        mu_ = mu_.reshape(3,)
        w_sample = np.random.multivariate_normal(mu_,var_cov)
        price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (w_sample),bounds = [(pl,ph)])["x"][0]
        p_curr = p_vector(price_estimate)
        p_array.append(price_estimate)
        epsilon = max(0,100-reven_array[-1])
        # epsilon =np.max([0,np.min(323.608 - np.array(reven_array))])
        error += epsilon
        epsilon_array.append(error)
    return np.array(epsilon_array),reven_array

def BayesOpt():
    epsilon_array = []
    train_x = torch.rand(2)
    train_y = []
    for price in train_x.numpy():
      train_y.append(func_revenue(price))
    train_y = np.array(train_y)
    train_y = torch.tensor(train_y)
    class ExactGPModel(gpytorch.models.ExactGP):
          def __init__(self, train_x, train_y, likelihood):
              super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
              self.mean_module = gpytorch.means.ConstantMean()
              self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

          def forward(self, x):
              mean_x = self.mean_module(x)
              covar_x = self.covar_module(x)
              return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
    # initialize likelihood and model
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = ExactGPModel(train_x, train_y, likelihood)

    def tune_hyperparameter(train_x,train_y):
          # print(train_x)
          # print(train_y)
          likelihood = gpytorch.likelihoods.GaussianLikelihood()
          model = ExactGPModel(train_x, train_y, likelihood)
          model.train()
          likelihood.train()

          optimizer = torch.optim.Adam(model.parameters(),lr = 0.1)

          mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood,model)

          training_iter = 100

          for i in range(training_iter):
                ##zero greadients from previous iterations

                optimizer.zero_grad()
                ##output from model

                output = model(train_x)

                ##calculate loss and backprop gradients

                loss = -mll(output,train_y)
                # print(loss)

                loss.backward()

                optimizer.step()

    tune_hyperparameter(train_x,train_y)

    def acquisition(model,train_x,Xsamples):
          train_x = torch.tensor(train_x)
          Xsamples = torch.tensor(Xsamples)
          # print(Xsamples)
          model.double()
          yhat = model(train_x).mean.detach().numpy()
          # print(yhat)
          best = max(yhat)
          model.eval();
          likelihood.eval();
          with torch.no_grad():
            f_preds = model(Xsamples)
          mu = (f_preds.mean).detach().numpy()
          std = ((f_preds.variance).detach().numpy()) ** 0.5
          # print(mu)
          # print(std)
          probs = (mu-best)*norm.cdf((mu-best)/(std+1e-9)) + std*norm.pdf((mu-best)/(std+1e-9))
          return probs
    def opt_acquisition(model,train_x):
          Xsamples = np.random.uniform(low = 0.353,high = 10,size = 10)
          scores = acquisition(model,train_x,Xsamples)
          ix = np.argmax(scores)
          # print(ix)
          return Xsamples[ix]



    train_x = train_x.numpy()
    train_y = train_y.numpy()
    for i in range(100):

      point = opt_acquisition(model,train_x)
      true_val = func_revenue(point)
      # print(true_val)
      # print(point)
      # train_x = train_x.numpy()
      # train_y = train_y.numpy()
      train_x = np.hstack((train_x,[point]))
      train_y = np.hstack((train_y,[true_val]))
      # print(train_x)
      # print(train_y)
      tune_hyperparameter(torch.tensor(train_x),torch.tensor(train_y))
      reven_array = train_y[2:]
      epsilon =np.max([0,np.min(323.608- np.array(reven_array))])
      epsilon_array.append(epsilon)
    return np.array(epsilon_array)

def ParameterSpace():
    epsilon_array = []
    mu_ = np.random.uniform(size = 3)
    # mu_ = np.array([-145,450,-150,10,-0.3])
    sigma_ = np.random.uniform(size= 3)
    def p_vector(p):
        p_arr = np.array([1,p,p**2])
        return p_arr

    def g_fun(p,*args):
        p_vec = np.array([1,p,p**2])
        coeff_array = args
        return -np.sum(coeff_array*p_vec)
    w = mu_ + sigma_ * np.random.normal(0,1)
    pl = 0.
    ph = 2.
    price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (w),bounds = [(pl,ph)])["x"][0]
    p_array = []
    reven_array_true = []
    p_curr = p_vector(price_estimate)
    p_array.append(price_estimate)
    alpha = 0.05
    error = 0
    for t in tqdm(range(1,101)):
        # rev_curr = (true_coeff.reshape(1,len(true_coeff))@p_curr.reshape(len(p_curr),1))[0][0]+np.random.normal(0,10)
        rev_curr = func_revenue(price_estimate)+np.random.normal(0,10)
    #     rev_curr_predict = (w.reshape(1,5)@p_curr)[0][0]
    #     print(rev_curr)
        reven_array_true.append(rev_curr)
    #     reven_array_predicted.append(rev_curr_predict
        sigma_ = sigma_*np.random.normal(0,1)
        mu = torch.tensor(mu_.reshape(len(mu_),1),requires_grad = True)
        sigma = torch.tensor(sigma_.reshape(len(sigma_),1),requires_grad = True)
        sum = torch.tensor([0])
        for i in range(len(p_array)):
            p_vec = p_vector(p_array[i])
            p_vec = p_vec.reshape(len(p_vec),1)
            p_vec = torch.tensor(p_vec)
            revenue = reven_array_true[i]
            sum =sum + ((torch.transpose(mu+sigma,0,1)@p_vec - torch.tensor([[revenue]]))**2)/t
        # print(sum.size())
        external_grad = torch.tensor([[1]])
        sum.backward(gradient = external_grad)
        mu_ = (mu- alpha*mu.grad).detach().numpy()
        sigma_ = (sigma - alpha*sigma.grad).detach().numpy()
        w = mu_ + sigma_ * np.random.normal(0,1)
    #     print(w)
        price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (w),bounds = [(pl,ph)])["x"][0]
        p_array.append(price_estimate)
        p_curr = p_vector(price_estimate)
        # print(p_curr)
        epsilon = max(0,100-reven_array_true[-1])
        # epsilon =np.max([0,np.min(323.608 - np.array(reven_array_true))])
        error += epsilon
        epsilon_array.append(error)
    return np.array(epsilon_array),reven_array_true

best_till_now_PS = []
reven_PS = []
for i in range(10):
  _,rets = ParameterSpace()
  reven_PS.append(rets)
  # cum_regret_PS.append(ParameterSpace())
  # best_till_now_PS.append(ParameterSpace())

target_PS = np.mean(reven_PS,axis = 0)

target_PS

# import matplotlib.pyplot as plt
# plt.plot(np.log10(cum_regret_PS[0]));
# plt.plot(np.log10(cum_regret_thmp[0]))

# import pickle
# file_p = open("Thmp7000_cum.txt","wb")
# pickle.dump(cum_regret_thmp[0],file_p)

# cum_regret_PS[0]

# import matplotlib.pyplot as plt
# plt.figure(figsize = (10,8))
# plt.plot(best_till_now_BO[0])
# plt.plot(best_till_now_BO[1])
# plt.plot(best_till_now_BO[2])
# plt.plot(best_till_now_BO[3])
# plt.plot(best_till_now_BO[4])
# plt.plot(best_till_now_BO[5])
# plt.plot(best_till_now_BO[6])
# plt.plot(best_till_now_BO[7])
# plt.plot(best_till_now_BO[8])
# plt.plot(best_till_now_BO[9])

best_till_now_thmp = []
reven_thmp = []
for i in range(10):
  _,rets = Thompson()
  reven_thmp.append(rets)

target_thmp = np.mean(reven_thmp,axis = 0)

target_thmp

# plt.plot(np.log10(cum_regret_thmp[0]))

plt.figure(figsize = (10,8))
plt.plot(best_till_now_thmp[0])
plt.plot(best_till_now_thmp[1])
plt.plot(best_till_now_thmp[2])
plt.plot(best_till_now_thmp[3])
plt.plot(best_till_now_thmp[4])
plt.plot(best_till_now_thmp[5])
plt.plot(best_till_now_thmp[6])
plt.plot(best_till_now_thmp[7])
plt.plot(best_till_now_thmp[8])
plt.plot(best_till_now_thmp[9])

best_till_Bo_averaged = np.mean(best_till_now_BO,axis = 0)
plt.figure(figsize = (10,8))
plt.plot(best_till_Bo_averaged)

best_till_tmp_avg = np.mean(best_till_now_thmp,axis = 0)
plt.figure(figsize = (10,8))
plt.plot(best_till_tmp_avg)

best_till_now_PS_avg = np.mean(best_till_now_PS,axis = 0)

"""## Greedy and Constrained ILS"""

# true_coeff = np.array([-150,480,-165,22,-1])
true_coeff = np.array([0,1.1,-0.5])

from scipy.optimize import minimize

def generate_demand(p):
  # p_vec = np.array([1,p,p**2])
  # d_vec = np.sum(true_coeff*p_vec)
  return 100*np.exp(-(p-5)**2/20) + np.random.normal(0,3)

def f_fun(coeff_array,*args):
  sum = 0
  p_arr,d_arr = args
  for i in range(len(p_arr)):
    p = p_arr[i]
    p_vec = np.array([1,p,p**2])
    demo_demand = np.sum(coeff_array*p_vec)
    # demo_demand = func_revenue(p)
    sum += (d_arr[i]-demo_demand)**2
  # print(sum)
  return sum

def g_fun(p,*args):
  coeff_array = args
  p_vec = np.array([1,p,p**2])
  # print(-np.sum(p_vec*coeff_array))
  return -np.sum(p_vec*coeff_array)

pl = 0.
ph = 20.

def GreedyILS():
  p_demo = np.random.uniform(low = pl,high = ph,size = 1)[0]
  d_demo = generate_demand(p_demo)
  p_array = []
  d_array = []
  p_array.append(p_demo)
  d_array.append(d_demo)
  epsilon_array = []
  for t in tqdm(range(1,101)):
    coeff_estimate = minimize(f_fun,x0 =np.random.random_sample(size = (3,)),args = (p_array,d_array),bounds = [(-50.,50.),(-50.,50.),(-50.,50.)] )["x"]
    # print(coeff_estimate)
    coeff_estimate = np.array(coeff_estimate)
    # print(coeff_estimate)
    price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (coeff_estimate),bounds = [(pl,ph)])["x"][0]
    p_array.append(price_estimate)
    d_new = generate_demand(price_estimate)
    d_array.append(d_new)
    # reven_array = np.array(p_array)*np.array(d_array)
    epsilon =np.max([0,np.min(100 - np.array(d_array))])
    epsilon_array.append(epsilon)
  return np.array(epsilon_array),d_array

best_till_now_greedy = []
reven_GILS = []
for i in tqdm(range(10)):
  _,rets = GreedyILS()
  reven_GILS.append(rets)
  # best_till_now_greedy.append(GreedyILS())

target_GILS = np.mean(reven_GILS,axis = 0)

target_GILS

k = 6

def ConstrainedILS():
  p_demo = np.random.uniform(low = pl,high = ph,size = 1)[0]
  d_demo = generate_demand(p_demo)
  p_array = []
  d_array = []
  p_array.append(p_demo)
  d_array.append(d_demo)
  epsilon_array = []
  for t in tqdm(range(1,101)):
    coeff_estimate = minimize(f_fun,x0 =np.random.random_sample(size = (3,)),args = (p_array,d_array),bounds = [(-50.,50.),(-50.,50.),(-50.,50.)] )["x"]
    # print(coeff_estimate)
    coeff_estimate = np.array(coeff_estimate)
    # print(coeff_estimate)
    price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (coeff_estimate),bounds = [(pl,ph)])["x"][0]
    p_t = p_array[len(p_array)-1]
    p_bar = np.mean(p_array)
    delta = p_t - p_bar
    if abs(delta)<k*(t**(-0.25)):
      price_estimate = p_t + np.sign(delta)*k*(t**(-0.25))
    p_array.append(price_estimate)
    d_new = generate_demand(price_estimate)
    d_array.append(d_new)
    # reven_array = np.array(p_array)*np.array(d_array)
    epsilon =np.max([0,np.min(100 - np.array(d_array))])
    epsilon_array.append(epsilon)
  return np.array(epsilon_array),d_array

best_till_now_cons = []
reven_CILS = []
for i in tqdm(range(10)):
  _,rets = ConstrainedILS()
  reven_CILS.append(rets)
  # best_till_now_cons.append(ConstrainedILS())

target_CILS = np.mean(reven_CILS,axis = 0)

target_CILS

# best_till_now_avg_GLS  = np.mean(best_till_now_greedy,axis = 0)
# best_till_now_avg_CLS = np.mean(best_till_now_cons,axis = 0)

"""## Action space exploration



"""

# true_coeff = np.array([-150,480,-165,22,-1])
true_coeff = np.array([0,1.1,-0.5])

def ActionSpace():
    epsilon_array = []
    epsilon_array2 = []
    epsilon_array3 = []
    mu_ = np.random.uniform(size = 3)
    sigma_ = np.random.uniform(size= 3)
    mu2 = np.random.uniform(size = 3)
    sigma2 = np.random.uniform(size = 3)
    mu3 = np.random.uniform(size = 3)
    sigma3 = np.random.uniform(size = 3)
    def p_vector(p):
        p_arr = np.array([1,p,p**2])
        return p_arr

    def g_fun(p,*args):
        p_vec = np.array([1,p,p**2])
        coeff_array = args
        return -np.sum(coeff_array*p_vec)
    w = mu_
    w2 = mu2
    w3 = mu3
    pl = 0.
    ph = 2.
    price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (w),bounds = [(pl,ph)])["x"][0]
    price_estimate2 = minimize(g_fun,x0 = np.array([random.random()]),args = (w2),bounds = [(pl,ph)])["x"][0]
    price_estimate3 = minimize(g_fun,x0 = np.array([random.random()]),args = (w3),bounds = [(pl,ph)])["x"][0]
    # price_estimate_arr = np.array([price_estimate,price_estimate2,price_estimate3])
    p_array = []
    reven_array_true = []
    p_array2 = []
    reven_array2 = []
    p_array3 = []
    reven_array3 = []
    p_curr = p_vector(price_estimate)
    p_array.append(price_estimate)
    p_curr2 = p_vector(price_estimate2)
    p_array2.append(price_estimate2)
    p_curr3 = p_vector(price_estimate3)
    p_array3.append(price_estimate3)
    # print(f"My price estimate {price_estimate3} ")
    alpha = 0.05
    # print(p_array)
    for t in tqdm(range(1,101)):
        # rev_curr = np.sum(true_coeff*p_curr)+np.random.normal(0,3)
        rev_curr = func_revenue(price_estimate) + np.random.normal(0,3)
    #     rev_curr_predict = (w.reshape(1,5)@p_curr)[0][0]
    #     print(rev_curr)
        reven_array_true.append(rev_curr)
    #     reven_array_predicted.append(rev_curr_predict
        # sigma_ = sigma_*np.random.normal(0,1)
        mu = torch.tensor(mu_.reshape(len(mu_),1),requires_grad = True)
        # print(f"My mean {mu}")
        # print(f"My transpose {torch.transpose(mu,0,1)}")
        # sigma = torch.tensor(sigma_.reshape(len(sigma_),1),requires_grad = True)
        sum = torch.tensor([0])
        # print(p_array)
        # print(f"we are in time: {t}")
        # print(reven_array_true)
        for i in range(len(p_array)):
            p_vec = p_vector(p_array[i])
            # print(p_vec)
            p_vec = p_vec.reshape(len(p_vec),1)
            # print(p_vec)
            p_vec = torch.tensor(p_vec)
            revenue = reven_array_true[i]
            sum =sum + ((torch.transpose(mu,0,1)@p_vec - torch.tensor([[revenue]]))**2)/t
        # print(torch.transpose(mu,0,1)@p_vec)
        # print(revenue)
        external_grad = torch.tensor([[1]])
        sum.backward(gradient = external_grad)
        # print(f"My gradient {mu.grad}")
        mu_ = (mu- alpha*mu.grad).detach().numpy()
        # sigma_ = (sigma - alpha*sigma.grad).detach().numpy()
        w = mu_
    #     print(w)
        price_estimate = minimize(g_fun,x0 = np.array([random.random()]),args = (w),bounds = [(pl,ph)])["x"][0]
        epsi = np.exp(-(t-1))
        unif = np.random.uniform(size = 1)
        if unif < epsi:
          price_estimate = np.random.uniform(low = pl,high = ph,size  = 1)[0]
        p_array.append(price_estimate)
        p_curr = p_vector(price_estimate)
        # print(p_curr)
        epsilon = np.max([0,np.min(100 - np.array(reven_array_true))])
        epsilon_array.append(epsilon)





    # for second starting point
    for t in tqdm(range(1,101)):
        # rev_curr2 = np.sum(true_coeff*p_curr2)+np.random.normal(0,3)
        rev_curr2 = func_revenue(price_estimate2)+np.random.normal(0,3)
    #     rev_curr_predict = (w.reshape(1,5)@p_curr)[0][0]
    #     print(rev_curr)
        reven_array2.append(rev_curr2)
    #     reven_array_predicted.append(rev_curr_predict
        # sigma2 = sigma2*np.random.normal(0,1)
        mu = torch.tensor(mu2.reshape(len(mu2),1),requires_grad = True)
        # sigma = torch.tensor(sigma2.reshape(len(sigma2),1),requires_grad = True)
        sum = torch.tensor([0])
        for i in range(len(p_array2)):
            p_vec = p_vector(p_array2[i])
            p_vec = p_vec.reshape(len(p_vec),1)
            p_vec = torch.tensor(p_vec)
            revenue = reven_array2[i]
            sum =sum + ((torch.transpose(mu,0,1)@p_vec - torch.tensor([[revenue]]))**2)/t
        # print(sum.size())
        external_grad = torch.tensor([[1]])
        sum.backward(gradient = external_grad)
        # print(f"My gradient {mu.grad}")
        mu2 = (mu- alpha*mu.grad).detach().numpy()
        # sigma2 = (sigma - alpha*sigma.grad).detach().numpy()
        w2 = mu2
    #     print(w)
        price_estimate2 = minimize(g_fun,x0 = np.array([random.random()]),args = (w2),bounds = [(pl,ph)])["x"][0]
        epsi = np.exp(-(t-1))
        unif = np.random.uniform(size = 1)
        if unif < epsi:
          price_estimate2 = np.random.uniform(low = pl,high = ph,size  = 1)[0]
        p_array2.append(price_estimate2)
        p_curr2 = p_vector(price_estimate2)
        # print(p_curr)
        epsilon = np.max([0,np.min(100 - np.array(reven_array2))])
        epsilon_array2.append(epsilon)







    # for third starting point
    for t in tqdm(range(1,101)):
        # rev_curr3 = np.sum(p_curr3*true_coeff)+np.random.normal(0,3)
        rev_curr3 = func_revenue(price_estimate) + np.random.normal(0,3)
    #     rev_curr_predict = (w.reshape(1,5)@p_curr)[0][0]
    #     print(rev_curr)
        reven_array3.append(rev_curr3)
    #     reven_array_predicted.append(rev_curr_predict
        # sigma3 = sigma3*np.random.normal(0,1)
        mu = torch.tensor(mu3.reshape(len(mu3),1),requires_grad = True)
        # sigma = torch.tensor(sigma3.reshape(len(sigma3),1),requires_grad = True)
        sum = torch.tensor([0])
        for i in range(len(p_array3)):
            p_vec = p_vector(p_array3[i])
            p_vec = p_vec.reshape(len(p_vec),1)
            p_vec = torch.tensor(p_vec)
            revenue = reven_array3[i]
            sum =sum + ((torch.transpose(mu,0,1)@p_vec - torch.tensor([[revenue]]))**2)/t
        # print(sum.size())
        external_grad = torch.tensor([[1]])
        sum.backward(gradient = external_grad)
        mu3 = (mu- alpha*mu.grad).detach().numpy()
        # sigma3 = (sigma - alpha*sigma.grad).detach().numpy()
        w3 = mu3
    #     print(w)
        price_estimate3 = minimize(g_fun,x0 = np.array([random.random()]),args = (w3),bounds = [(pl,ph)])["x"][0]
        epsi = np.exp(-(t-1))
        unif = np.random.uniform(size = 1)
        if unif < epsi:
          price_estimate3 = np.random.uniform(low = pl,high = ph,size  = 1)[0]
        p_array3.append(price_estimate3)
        p_curr3 = p_vector(price_estimate3)
        # print(p_curr)
        epsilon = np.max([0,np.min(100 - np.array(reven_array3))])
        epsilon_array3.append(epsilon)



    e= np.array([np.min(epsilon_array),np.min(epsilon_array2),np.min(epsilon_array3)])
    ex = np.argmin(e)
    if ex == 0:
      return np.array(epsilon_array),reven_array_true
    if ex == 1:
      return np.array(epsilon_array2),reven_array2
    if ex == 2:
      return np.array(epsilon_array3),reven_array3

best_till_now_AS = []
reven_AS = []
for i in tqdm(range(10)):
  _,rets = ActionSpace()
  reven_AS.append(rets)
  # best_till_now_AS.append(ActionSpace())
# np.mean(best_till_now)

target_AS = np.mean(reven_AS,axis = 0)

target_AS

import pickle

file_pathPS = open("PS_exp.txt","wb")
file_pathAS = open("AS_exp.txt","wb")
file_pathT = open("thmp_exp.txt","wb")
file_pathCILS = open("CILS_exp.txt","wb")
file_pathGILS = open("GILS_exp.txt","wb")

pickle.dump(target_PS,file_pathPS)
file_pathPS.close()
pickle.dump(target_AS,file_pathAS)
file_pathAS.close()
pickle.dump(target_thmp,file_pathT)
file_pathT.close()
pickle.dump(target_CILS,file_pathCILS)
file_pathCILS.close()
pickle.dump(target_GILS,file_pathGILS)
file_pathGILS.close()

arr

plt.figure(figsize = (10,8))
plt.plot(best_till_tmp_avg,label = "Thompson_Sampling")
plt.plot(best_till_Bo_averaged,label = "BayesOpt")
plt.plot(best_till_now_PS_avg,label = "ParameterSpace")
plt.plot(best_till_now_avg_CLS,label = "CILS")
plt.plot(best_till_now_AS_avg,label = "Action Space")
# plt.plot(best_till_now_avg_GLS,label = "GILS")
plt.xlabel("Budget")
plt.ylabel("Best till now Regret")
plt.title("y =-x^4 + 22*x^3-165*x^2 +480x-150 ")
plt.legend()
plt.savefig("Result_for_second_test_function.png")
plt.savefig("4_degree_polynomial_infinite.png")

import pickle

file_path = open("/content/PS7000_cum.txt","rb")
file_path2 = open("/content/Thmp7000_cum.txt","rb")

PS_array = pickle.load(file_path)

Thmp_array = pickle.load(file_path2)

import matplotlib.pyplot as plt

plt.figure(figsize = (10,8))
plt.plot(PS_array,label = "Parametyer Space")
plt.plot(Thmp_array, label = "Thompson")
plt.legend()

